#!/usr/bin/env node
/* build.js — สร้างไฟล์สำหรับเซิร์ฟเวอร์จาก ac711.html (แหล่งเดียว)
   1) build/tenant-api.js  : โค้ด API ของร้าน (บล็อกสุดท้ายของ ac711.html) ห่อเป็น factory ต่อผู้เช่า 1 ราย
   2) public/index.html    : หน้าเว็บ = ac711.html ตัดบล็อก backend จำลองออก + ธง window.AC711_SERVER */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = process.env.AC711_SRC || [path.join(ROOT, 'ac711.html'), path.join(ROOT, '..', 'ac711.html')].find(p => fs.existsSync(p));
if (!SRC) throw new Error('ไม่พบไฟล์ ac711.html (ต้องอยู่ที่ root ของโปรเจกต์)');
const html = fs.readFileSync(SRC, 'utf8');

const re = /<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/g;
const blocks = []; let m;
while ((m = re.exec(html))) blocks.push({ start: m.index, end: m.index + m[0].length, code: m[1] });
const last = blocks[blocks.length - 1];
if (!/const SEED_CATS = \[/.test(last.code) || !/const R = \[\];/.test(last.code)) throw new Error('ไม่พบบล็อก backend จำลองใน ac711.html');

/* ---------- 1) tenant-api.js ---------- */
let code = last.code;
// ตัดส่วนท้ายที่ผูกกับเบราว์เซอร์ (seed อัตโนมัติ, API.req override, window.AC711_DEMO, App.boot)
const tailStart = code.indexOf('  seed(); finBackfill(); hrSeed(); attSeed();');
if (tailStart < 0) throw new Error('ไม่พบบรรทัด seed() ท้ายบล็อก');
const iifeEnd = code.lastIndexOf('})();');
if (iifeEnd < tailStart) throw new Error('โครงสร้าง IIFE ไม่ตรงที่คาด');
code = code.slice(0, tailStart) +
  `  __expose({ DB, R, ins, by, applyReset, tick, forecastProduct, userView, audit, docCode, nowStr, err, permsFor, staffPerms,
    setUser: u => { USER = u; }, getUser: () => USER,
    seedAll: () => { seed(); finBackfill(); hrSeed(); attSeed(); },
    setEmitHook: fn => { EMIT_HOOK = fn; } });\n` + code.slice(iifeEnd, iifeEnd + '})();'.length) + '\n';   // ตัด App.boot() ที่ตามหลัง IIFE
// emit() → ส่งต่อให้ host (SSE) ด้วย
code = code.replace('function emit(ev, data) {', 'function emit(ev, data) { if (typeof EMIT_HOOK === \'function\') { try { EMIT_HOOK(ev, data); } catch {} }');
if (!code.includes('EMIT_HOOK(ev, data)')) throw new Error('แก้ emit() ไม่สำเร็จ');
// window.AC711_FIN / window.AC711_HR ถูกอ้างถึงแบบ global ในโค้ด route → ประกาศตัวแปรไว้ในสโคปโมดูล (hoisted globals)
const globals = [...new Set([...code.matchAll(/window\.(AC711_[A-Z_]+) = /g)].map(m => m[1]))];
globals.forEach(g => { code = code.split('window.' + g + ' = ').join(g + ' = window.' + g + ' = '); });
const iifeStart = code.indexOf('(function () {');
code = code.slice(0, iifeStart) + '(function () {\n  let EMIT_HOOK = null;' + (globals.length ? ' let ' + globals.join(', ') + ';' : '') + code.slice(iifeStart + '(function () {'.length);

const wrapped = `/* GENERATED by scripts/build.js from ac711.html — ห้ามแก้ไฟล์นี้โดยตรง */
'use strict';
module.exports = function createTenantApi(host = {}) {
  const PAGE_TABS = host.PAGE_TABS || {};
  const localStorage = host.localStorage || { getItem: () => null, setItem() {}, removeItem() {} };
  const window = host.window || {};
  const Site = host.Site || { log() {}, seedAccounts() {}, expiry: () => null };
  const App = host.App || { sse: [], logout() {}, refreshCounts() {} };
  const API = host.API || {};
  const UI = host.UI || {};
  const dd = host.dd || (s => String(s || '').slice(0, 10));
  const setTimeout = host.setTimeout || ((fn) => { try { fn(); } catch {} });
  let exposed = null; const __expose = o => { exposed = o; };
${code}
  return exposed;
};
`;
fs.mkdirSync(path.join(ROOT, 'build'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'build', 'tenant-api.js'), wrapped);

/* ---------- 2) public/index.html ---------- */
let web = html.slice(0, last.start) + '<script>App.boot();</script>' + html.slice(last.end);
web = web.replace('<script>', '<script>window.AC711_SERVER = true;</script>\n<script>');
fs.mkdirSync(path.join(ROOT, 'public'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'public', 'index.html'), web);

// ตรวจว่า factory โหลดได้และมี route ครบ
const api = require(path.join(ROOT, 'build', 'tenant-api.js'))();
console.log(`build ok: tenant-api.js (${api.R.length} routes), public/index.html (${(web.length / 1024).toFixed(0)} KB)`);
